### ISSUE TITLE
Use with react-redux

### ISSUE THREAD

**Issue by suyang-nju** [logux/redux#12]
The README says `store.dispatch()` is legacy api and advises in favor of `store.dispatch.local()`/`crossTab()`/`sync()`, but react-redux passes the store's `dispatch` method in `connect()`. Is there a way to use the new methods in react-redux?

**Comment by ai** [comment]
`dispatch` from `react-redux` already have `dispatch.*` Logux extensions.

```js
dispatch => {
  onAdd (data) {
    dispatch.sync(data)
  }
}
```
