### ISSUE TITLE
Undocumented option "checkEvery" in LoguxReduxConfig.

### ISSUE THREAD

**Issue by nikolay-govorov** [logux/redux#22]
Hi. The [createLoguxCreator code](https://github.com/logux/redux/blob/master/create-logux-creator/index.js#L17) has an undocumented `checkEvery` parameter. It affects how often the history cleanup will be started.

It was omitted on purpose, or should I add it to the [`LoguxReduxConfig`](https://github.com/logux/redux/blob/master/create-logux-creator/index.d.ts#L133)?

**Comment by ai** [comment]
Wait for a second, I will add docs

**Comment by ai** [comment]
I renamed the name and added docs e9a8968
