### ISSUE TITLE
Troubles with dispatch types in connect

### ISSUE THREAD

**Issue by dotterian** [logux/redux#25]
Redux's `connect` implores that `dispatch` is of type `Redux.Dispatch`, hence we can't use `LoguxDispatch` and code like this will produce errors:
```typescript
connect(null, dispatch => ({
  doSomething: () => dispatch.sync({ type: 'SOME_ACTION' }) // Property 'sync' does not exist on type 'Dispatch<Action<any>>'
}))(SomeComponent)
```
Extracting MapDispatchToProps into separate variable with parameter type of LoguxDispatch also breaks things:
```typescript
const mapDispatchToProps = (dispatch: LoguxDispatch<Action>) => ({
  doSomething: () => dispatch.sync({ type: 'SOME_ACTION' })
})

connect(null, mapDispatchToProps)(SomeComponent) // No overload matches this call
```

At the time I have no ideas how to solve this problem except `// @ts-ignore`, which is obviously bad.

One possible (but not so good) solution that comes to my mind is to export `connect` from `@logux/redux` with modified typescript signatures.

**Comment by ai** [comment]
Am I right that it is TS only problem and you will see `sync` property in the browser?

**Comment by dotterian** [comment]
Yes, it's types related and if I ignore typechecking for this line it works perfectly.

**Comment by ai** [comment]
`connect` is Redux method, do you have any idea how to fix types there?

**Comment by ai** [comment]
Sorry, have no idea how to fix it for now
