### ISSUE TITLE
Different behaviour in different browsers

### ISSUE THREAD

**Issue by devgru** [logux/redux#3]
This example demonstrates that in some cases logux behaves differently in different browsers.

**How to reproduce:**
Clone this repo https://github.com/devgru/logux-firefox-behaviour
Install packages: `yarn` 
Run logux server: `node server.js`
Run web-server: `yarn start`
Open `http://localhost:3000` in a browser.

Page will display JSON state of redux store.

**Expectations:**

Page behave the same way in all modern browsers.

**Result:**

In Chrome we will see initial store state (`{someState: 1}`), in Firefox and Safari we get `{}`. Looks like reducer is called without action and with empty state (`{}`).

**Comment by ai** [comment]
Thanks for demo project!

**Comment by ai** [comment]
I think we can close it for now, since we have a few big refactoring
